version: "3"

services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: on-failure
    command: ["--smtp-auth-allow-insecure"]
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - ./data:/data
    environment:
      MP_SMTP_AUTH_ALLOW_INSUCURE: 1
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_DATA_FILE: /data/mailpit.db

  db:
    image: postgres:14-alpine
    env_file: .env
    container_name: db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '6432:5432'

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=UTC    # optional: set desired timezone
    volumes:
      - ./data/var/cache/ntfy:/var/cache/ntfy
      - ./data/etc/ntfy:/etc/ntfy
    ports:
      - 5012:80
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
